"""update database untuk attendancec

Revision ID: e2a28fe8dadb
Revises: 2b73a2753b72
Create Date: 2024-12-18 02:30:55.792140

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2a28fe8dadb'
down_revision = '2b73a2753b72'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=9),
               type_=sa.Enum('ALPHA', 'IJIN', 'TIDAK_HADIR', 'HADIR', name='attendancestatus'),
               existing_nullable=False)
        batch_op.alter_column('date',
               existing_type=sa.DATETIME(),
               type_=sa.Date(),
               existing_nullable=False)
        batch_op.alter_column('time',
               existing_type=sa.DATETIME(),
               type_=sa.Time(),
               existing_nullable=False)
        batch_op.alter_column('time_out',
               existing_type=sa.DATETIME(),
               type_=sa.Time(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.alter_column('time_out',
               existing_type=sa.Time(),
               type_=sa.DATETIME(),
               existing_nullable=True)
        batch_op.alter_column('time',
               existing_type=sa.Time(),
               type_=sa.DATETIME(),
               existing_nullable=False)
        batch_op.alter_column('date',
               existing_type=sa.Date(),
               type_=sa.DATETIME(),
               existing_nullable=False)
        batch_op.alter_column('status',
               existing_type=sa.Enum('ALPHA', 'IJIN', 'TIDAK_HADIR', 'HADIR', name='attendancestatus'),
               type_=sa.VARCHAR(length=9),
               existing_nullable=False)

    # ### end Alembic commands ###
